# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="yes"
php:
  - 5.6

before_script:
  # Make sure all dev dependencies are installed
  - composer install
  - git clone https://github.com/joomla/coding-standards.git .tmp/Joomla/ --depth 1

script:
  - if [[ $RUN_PHPCS == "yes" ]]; then vendor/bin/phpcs --report=full --extensions=php -p --standard=.tmp/Joomla src; fi
